### ISSUE TITLE
Build process doesn't react to .rs files being modified

### ISSUE THREAD

**Issue by robertohuertasm** [wasm-tool/wasm-pack-plugin#10]
It would be nice if the loader could react to `.rs` files being modified. Otherwise, the watch mode is useless as it only works now if the `Cargo.toml` file is modified.

**Comment by xtuc** [comment]
Yeah that's a known issue, we're trying to solve it here as well https://github.com/rustwasm/rust-webpack-template/pull/7.

**Comment by xtuc** [comment]
Has been fixed in `@wasm-tool/wasm-pack-plugin` (which replaces the old loader).
