### ISSUE TITLE
wasm-pack-plugin doesnt work well with yarn

### ISSUE THREAD

**Issue by tanay-pingalkar** [wasm-tool/wasm-pack-plugin#108]
i was using yarn. And when i do yarn start, it shows that `the crate has been compile` etc... but doesnt make any difference. When i use my change, it shows that it doest exist. I tried manually installing the ./pkg again, but still after lot of tries, it shows changes. Then i delete node_modules and yarn.lock and installed all dependencies using `npm install`, and now everything is wokring file.
Does wasm-pack-plugin support yarn??

**Comment by xtuc** [comment]
The plugin supports yarn https://github.com/wasm-tool/wasm-pack-plugin/blob/master/plugin.js#L136-L137

**Comment by tedbyron** [comment]
@tanay-pingalkar use a yarn `portal` if you have the `wasm-pack` output package specified as a dependency:

```js
// file: package.json

// ...
"dependencies": {
  "my-wasm-pkg": "portal:./pkg",
}
```

or else yarn will use a cached version of the package from `.yarn/cache/` and you have to `yarn install` every time `pkg/` is built
