### ISSUE TITLE
WasmPackPlugin running multiple builds in parallel?

### ISSUE THREAD

**Issue by robert-chiniquy** [wasm-tool/wasm-pack-plugin#112]
Hi! I don't know if this is a bug in wasm-pack-plugin or in webpack, but I could really use help, so I'm asking here. I've checked the existing issues and I'm surprised that I don't seem to see other mentions of it.

It seems like either webpack is kicking off multiple parallel runs of wasm-pack-plugin, where it should only start 1, or possibly that wasm-pack-plugin has multiple callbacks running in parallel where only 1 is intended. The number of parallel filesystem watching jobs seems to stack up non-deterministically as I work, I've gotten up to maybe 9 of them at times.

I've experienced this issue in multiple projects with multiple very different setups, but it is currently happening to me with webpack 5 running under nextjs. It's happened to me before with very basic (no nextjs) webpack setups with webpack 4 too. 

If it's helpful I can put together a small example to reproduce it (I'm kind of hoping this is a known webpack issue that I can work around somehow).

Sometimes the only impact is that builds take longer, or the browser can't refresh, but sometimes it causes errors to be erroneously reported, breaking browser refresh, sometimes because `wasm-opt` stomps on itself during filesystem operations, other times the files in `wasm-pack`'s output directory are mangled.

Here's some example console output:

```
    Finished release [optimized + debuginfo] target(s) in 7.83s
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
Error: No such file or directory (os error 2)
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
[INFO]: ✨   Done in 42.88s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/rch/repo/app/web/public/pkg.
✅  Your crate has been correctly compiled

ℹ️  Compiling your crate in release mode...

ℹ️  Compiling your crate in release mode...

[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
[INFO]: 🌀  Compiling to Wasm...
   Compiling app v0.0.0 (/Users/rch/repo/app/app)
warning: `app` (lib) generated 3 warnings
    Finished release [optimized + debuginfo] target(s) in 7.50s
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
Error: No such file or directory (os error 2)
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
[INFO]: ✨   Done in 43.15s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/rch/repo/app/web/public/pkg.
```

Thanks! I really appreciate the code and work of this community. Let me know if I can add any clarity here.

**Comment by robert-chiniquy** [comment]
I fixed this by hacking the webpack config with a module-scoped flag to only load WasmPackPlugin the first time through. This hack is terrible but it does prove that this is not an issue with this code.

Thanks! I think filing this issue is what pushed me over the hump of fixing this. :duck:

**Comment by austintheriot** [comment]
Hi @robert-chiniquy, what steps did you take to only load WasmPackPlugin the first time through? I'm facing a similar issue and don't have a ton of Webpack experience, so looking for any solution here, even if it's mega hacky.

**Comment by robert-chiniquy** [comment]
@austintheriot Hey, so this was a long time ago, but the hack was something terrible like this ... grabbed it out of a diff so may be messy but illustrates the idea (use a module scoped flag declared outside of `module.exports`, check it in a closure), hope this helps:

```js
let already_loaded_wasmpack = false;
module.exports = withBundleAnalyzer({ webpack }) => {
if (!already_loaded_wasmpack) {
    already_loaded_wasmpack = true;
    config.plugins.push(new WasmPackPlugin({
        extraArgs: "--target web",
...
```

**Comment by austintheriot** [comment]
@robert-chiniquy thanks for the response! Much appreciated.
