### ISSUE TITLE
Version 1.5.0 is missing on this repo's Releases page

### ISSUE THREAD

**Issue by Keavon** [wasm-tool/wasm-pack-plugin#113]
Thanks for recently adding 1.5.0 to npm! I noticed that it, however, isn't listed on https://github.com/wasm-tool/wasm-pack-plugin/releases or https://github.com/wasm-tool/wasm-pack-plugin/tags. To avoid confusion to users, it would be helpful to keep both places updated.

It might also be nice to add the npm installation instructions to the readme, so it isn't only yarn listed.

**Comment by xtuc** [comment]
My bad, I forgot to push the commit and associated tag: https://github.com/wasm-tool/wasm-pack-plugin/commit/c07c0c13caa430930157076a30df43f8966a0467.

> It might also be nice to add the npm installation instructions to the readme, so it isn't only yarn listed.
sure, could you please send a PR?

**Comment by Keavon** [comment]
> sure, could you please send a PR?

Done: #114. Thanks!
