### ISSUE TITLE
What does this plugin actually do?

### ISSUE THREAD

**Issue by ahhshm** [wasm-tool/wasm-pack-plugin#126]
sorry, I'm new to webpack and wasm and I can't figure out what is the benefit of this plugin and what does it actually does? it is a loader for wasm files? what extra things happen if I run `npx webpack build` with this plugin enabled?

**Comment by art-in** [comment]
this plugin basically calls `wasm-pack` whenever needed, and that's it  

particular benefit is that it can watch for source file changes and call `wasm-pack` after each change.  
alternatively you would need to call it manually everytime, which is inconvenient.  
e.g. i like how you can start webpack dev server, ctrl+s in some `.rs` file, switch to browser and immediately see result.  

also it can install `wasm-pack` through `npm` or `yarn` if it wasn't found.

p.s. plugin's source is pretty simple and straightforward, so it can be easier to just read it yourself    
https://github.com/wasm-tool/wasm-pack-plugin/blob/master/plugin.js

**Comment by ahhshm** [comment]
Thanks for your clear explanation.
