### ISSUE TITLE
Incorrect version number in the example project

### ISSUE THREAD

**Issue by robertohuertasm** [wasm-tool/wasm-pack-plugin#19]
The `package.json` dependency for `@wasm-tool/wasm-pack-plugin` is now `0.0.1`. This seems to be an invalid version and an error is thrown. 

I've reviewed `npm` and the vesion history only shows `0.0.4.` and `0.0.5`.

I'm preparing a PR for this. :wink: 

While we're at it, I wanted you to ask why are we using the npm deployed package and not a local reference? Is this because you want people to be able to execute the example without having to also install the npm dependencies of the main project?

**Comment by xtuc** [comment]
I'm using yarn/npm link to use the local version anyway (which seems to ignore the version). I think it's better to reference the package on npm so that people can just copy/paste the code.

I don't mind changing it if that annoys you?

**Comment by robertohuertasm** [comment]
No, don't worry @xtuc! I was just curious about the rationale behind this decision. It's ok for me if this is for user's comfort. :stuck_out_tongue_winking_eye:
