### ISSUE TITLE
Check if `wasm-pack` is available in $PATH

### ISSUE THREAD

**Issue by xtuc** [wasm-tool/wasm-pack-plugin#22]
We should check it at the beginning and print a user-friendly error in case it doesn't exists.

**Comment by robertohuertasm** [comment]
I guess in case that `wasm-pack` were not installed we could check for `cargo` and spawn `cargo install wasm-pack`, before continuing with the process.

**Comment by xtuc** [comment]
Yes, that would be the best UX :+1:
