### ISSUE TITLE
Use `wasm-pack init` as `build` fallback

### ISSUE THREAD

**Issue by xtuc** [wasm-tool/wasm-pack-plugin#23]
Currently `wasm-pack build` hasn't been release yet and the template already relies on it. We could fall back to `wam-pack init` in the meantime.

**Comment by robertohuertasm** [comment]
@xtuc, remember #9. this could be easily fixed for the moment just changing `build` for `init`, as `init` is an alias for `build` in the new version. Once the new version of `wasm-pack` is getting released we can easily change it back. This way we don't have to check if the command fails or not.

**Comment by sendilkumarn** [comment]
That is really awesome and we can do that straightaway then 👍

**Comment by robertohuertasm** [comment]
Just as a reference: https://github.com/rustwasm/wasm-pack/blob/master/src/command/mod.rs#L23
