### ISSUE TITLE
Allow one-off builds

### ISSUE THREAD

**Issue by smasher816** [wasm-tool/wasm-pack-plugin#37]
WasmPackPlugin automatically watches for changed .rs files
https://github.com/wasm-tool/wasm-pack-plugin/blob/102c5002f4c4116762810368375f8e29c01a2760/plugin.js#L55-L58

while this is nice for live reloads with `webpack-dev-server`, it prevents calls to plain old `webpack` from ever exiting (for instance when generating a static dist folder for apache/nginx/etc) .

This feature is expected to work with `npm run build` in the official rust-webpack-template (https://github.com/rustwasm/rust-webpack-template/blob/2d89010a889e57191c3e7282643830b4fc38f3f7/package.json#L9)

**Comment by xtuc** [comment]
Interesting, indeed.

We could only watch those files when Webpack is configured in watch mode and otherwise use the same regexp to compile all the file once.

Do you want to work on it?
