### ISSUE TITLE
Environment is being cleared before launching wasm-pack

### ISSUE THREAD

**Issue by TheJare** [wasm-tool/wasm-pack-plugin#39]
This causes important env variables like CARGO_HOME to disappear in the child process. The three lines that set the environment in the options object at https://github.com/wasm-tool/wasm-pack-plugin/blob/master/plugin.js#L118 should be removed.

**Comment by xtuc** [comment]
That's a good point, I wanted to avoid polluting the env but doesn't really make sense. Would you mind sending a PR?
