### ISSUE TITLE
Manually configure build mode (debug/release)

### ISSUE THREAD

**Issue by power-fungus** [wasm-tool/wasm-pack-plugin#42]
I would like to be able to select within the webpack build script if `wasm-pack` is called with release/production or debug/development mode. Currently, this is done via webpack's `mode` configuration.

Background: I develop a tiny webapp where the computation-heavy task is written in rust. In `release` mode, a task takes 500ms, while in `debug` mode 20s. This difference is fine to me, but when developing the non-rust parts I would like to develop using webpack's `develop` mode but still use the `release` version of the rust package to avoid long waits.

If desired, I can create a PR to add a configuration option to this plugin.

**Comment by sendilkumarn** [comment]
@power-fungus I think this sounds great, let us do it. I am sure this will help others.

**Comment by xtuc** [comment]
Make sense to me, we recently added a `forceWatch` options. What about adding a `forceMode` which, when specified, bypasses the Webpack mode and apply the specified mode?

**Comment by power-fungus** [comment]
I would like to add the option `mode`. When given, `compiler.options.mode` is not queried. There would be 2 modes supported:
* `release`/`production`
* `debug`/`development`

The left ones are how they are called in cargo and the right ones are used by webpack. I would like to add all four options and match them to the 2 modes.

If this is fine, I would try to submit a pull-request
