### ISSUE TITLE
Doesn't appear to work with multiple configs being exported

### ISSUE THREAD

**Issue by liamcurry** [wasm-tool/wasm-pack-plugin#49]
This plugin doesn't appear to work when multiple configs are exported. For example, in `webpack.config.js`:

```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const WasmPackPlugin = require("@wasm-tool/wasm-pack-plugin");

module.exports = ["pkg1", "pkg2"].map(pkg=> ({
  entry: path.resolve(__dirname, pkg, "index.js"),
  output: {
    path: path.resolve(__dirname, "dist", pkg),
    filename: "bundle.js"
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new WasmPackPlugin({
      crateDirectory: path.resolve(__dirname, pkg)
    }),
  ]
}));
```

Docs on exporting multiple configs: https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations

Exporting multiple configs is useful when working in workspaces that should produce multiple `.wasm` files, like a project with a bunch of examples.

**Comment by xtuc** [comment]
Good catch, I never tested that. Would you mind sending a PR? I'll take a look at it.

**Comment by liamcurry** [comment]
@xtuc see PR #50
