### ISSUE TITLE
WASM breaks after passing through webpack

### ISSUE THREAD

**Issue by LaylConway** [wasm-tool/wasm-pack-plugin#53]
While the WASM coming out of wasm-pack is valid, what comes out of webpack using wasm-pack-plugin doesn't seem to be valid WASM. It can't be run in the browser and it can't be parsed by wasm2wat.

**Comment by LaylConway** [comment]
Here's a zip including both the input WASM and the output WASM:
[files.zip](https://github.com/wasm-tool/wasm-pack-plugin/files/2902868/files.zip)

**Comment by fitzgen** [comment]
I believe that the root cause is https://github.com/xtuc/webassemblyjs/pull/493 and we need dep upgrades to propagate out. cc @sendilkumarn @xtuc

**Comment by fitzgen** [comment]
Thanks for filing an issue @LaylConway!

**Comment by LaylConway** [comment]
When I get the server to replace the WASM file with the original one, I get instead the following error:
```
installedModules['./pkg/example_client.js'] is undefined
```
Not sure if this is because there are some necessary alterations needed to the WASM file. Tried to make a workaround but this is blocking that.

**Comment by LaylConway** [comment]
As an additional note, digging down more this issue only occurs when using `#[wasm_bindgen(start)]`

**Comment by sendilkumarn** [comment]
@LaylConway it is due to #[wasm_bindgen(start)] removing start will make it work till the webpack is updated.

**Comment by xtuc** [comment]
I believe this has been fixed since.
