### ISSUE TITLE
wasm-pack cannot be launched

### ISSUE THREAD

**Issue by fdietze** [wasm-tool/wasm-pack-plugin#56]
When including the plugin like this:
```javascript
module.exports.plugins.push(new WasmPackPlugin({
      crateDirectory: Path.resolve(__dirname, "crate"),
    }));
```

It always fails with:
```
wasm-pack error: Error: spawn wasm-pack ENOENT
```

Even though I have `wasm-pack` in `$PATH` and can launch it from the command line.
I can even launch it right before adding the plugin like this:
```javascript
childProcess.spawn("wasm-pack", {stdio: [process.stdin, process.stdout, process.stderr]});
```

what could be wrong?

**Comment by xtuc** [comment]
The plugin depends on wasm-pack, did you install it? see https://rustwasm.github.io/wasm-pack/installer/.

It's not explicit in our README, would you mind doing a PR?

**Comment by fdietze** [comment]
Thanks for the response. As I said, `wasm-pack` is installed and I can run it. I can even run it from the webpack-config. But the plugin does not find it.

**Comment by xtuc** [comment]
Indeed, sorry.

The plugin also uses spawn https://github.com/wasm-tool/wasm-pack-plugin/blob/master/plugin.js#L117, I'm wondering if we add
```
  env: process.env
```
in the options here https://github.com/wasm-tool/wasm-pack-plugin/blob/master/plugin.js#L108 if it would work, could you please try that?

**Comment by fdietze** [comment]
Actually my cwd didn't exist.

The problem was a misleading error message: https://github.com/nodejs/node/issues/11520

So a better error message in this plugin would be helpful here.
