### ISSUE TITLE
[Feature request] Enable custom output logging level (quiet, verbose, info, etc)

### ISSUE THREAD

**Issue by niedzielski** [wasm-tool/wasm-pack-plugin#79]
This is a feature request to enable the wasm-pack log level to be specified :+1:

Now that https://github.com/rustwasm/wasm-pack/pull/694 is merged and released, it should be possible to customize the output level wanted. As far as I can tell, [wasm-pack-plugin hardcodes this level to verbose](https://github.com/wasm-tool/wasm-pack-plugin/blob/80911d9/plugin.js#L175) so it's not easy to change the level to warn or quiet.

As mentioned in the [wasm-pack v0.9.0](https://github.com/rustwasm/wasm-pack/releases/tag/v0.9.0) release notes, these logging arguments must appear _before_ the command so wasm-pack-plugin's `extraArgs` property cannot be used. However, I think a new property, perhaps called simply `args`, could be added to allow for log level (or other options) to be passed and default to whatever makes sense (currently `--verbose`).

**Comment by xtuc** [comment]
I published `v1.2.0` with that feature

**Comment by niedzielski** [comment]
Thank you, @xtuc!
